set -x fish_color_command magenta
set -x fish_color_param blue
set -x fish_color_quote green
set -x fish_color_error red
set -x fish_color_redirection yellow
set -x fish_color_end yellow
set -x fish_color_comment brblack
set -x fish_color_operator blue
set -x fish_color_escape blue
set -x fish_color_autosuggestion brblack
